import 'package:flutter/material.dart';

class User extends Object {
  User(this.icon, this.name);

  IconData icon;
  String name;
}

var usrs = <User>[
  User(Icons.person, '刘嘉格'),
  User(Icons.person, '刘雨鑫'),
  User(Icons.person, '孙玮'),
  User(Icons.person, '杜艳'),
  User(Icons.person, '李芳雯'),
  User(Icons.person, '孔舒航'),
  User(Icons.person, '瞿颖'),
  User(Icons.person, '曹颖'),
  User(Icons.person, '于喆'),
  User(Icons.person, '柏安'),
  User(Icons.person, '张袁媛'),
  User(Icons.person, '佘南南'),
  User(Icons.person, '吴弘'),
  User(Icons.person, '张含韵'),
  User(Icons.person, '郭殿甲'),
  User(Icons.person, '罗杰'),
  User(Icons.person, '夏筠妍'),
  User(Icons.person, '周锐'),
  User(Icons.person, '黄锶骐'),
  User(Icons.person, '赵英俊'),
  User(Icons.person, '蔡文静'),
  User(Icons.person, '张南'),
  User(Icons.person, '金巧巧'),
  User(Icons.person, '杨翌'),
  User(Icons.person, '张哲'),
  User(Icons.person, '张馨予'),
  User(Icons.person, '张津铭'),
  User(Icons.person, '孙率航'),
  User(Icons.person, '张艺骞'),
  User(Icons.person, '韩庚'),
  User(Icons.person, '尹正'),
  User(Icons.person, '黄晓明'),
  User(Icons.person, '任东霖'),
  User(Icons.person, '王大治'),
  User(Icons.person, '关晓彤'),
  User(Icons.person, '刘锐'),
  User(Icons.person, '严禹豪'),
  User(Icons.person, '苏小明'),
  User(Icons.person, '贾媛媛'),
  User(Icons.person, '胡耘豪'),
  User(Icons.person, '宋家腾'),
  User(Icons.person, '陈昊宇'),
  User(Icons.person, '刘汉兆'),
  User(Icons.person, '冯青'),
  User(Icons.person, '李文乐'),
  User(Icons.person, '侍宣如'),
  User(Icons.person, '景岗山'),
  User(Icons.person, '冶彦'),
  User(Icons.person, '翟潇闻'),
  User(Icons.person, '张天其'),
  User(Icons.person, '蔡国庆'),
  User(Icons.person, '郑湫泓'),
  User(Icons.person, '李天佑'),
  User(Icons.person, '唐本'),
  User(Icons.person, '秦岚'),
  User(Icons.person, '隋柯名'),
  User(Icons.person, '范世錡'),
  User(Icons.person, '彭士腾'),
  User(Icons.person, '胡莎莎'),
  User(Icons.person, '赵梦迪'),
  User(Icons.person, '侯明昊'),
  User(Icons.person, '吴文璟'),
  User(Icons.person, '何其炜'),
  User(Icons.person, '厉娜'),
  User(Icons.person, '赵子麒'),
  User(Icons.person, '冯波'),
  User(Icons.person, '陈希郡'),
  User(Icons.person, '王嘉'),
  User(Icons.person, '杨菲洋'),
  User(Icons.person, '张哲瀚'),
  User(Icons.person, '谷嘉诚'),
  User(Icons.person, '蔡俊涛'),
  User(Icons.person, '徐冬冬'),
  User(Icons.person, '贾征宇'),
  User(Icons.person, '欧豪'),
  User(Icons.person, '袁泉'),
  User(Icons.person, '李茂'),
  User(Icons.person, '高毅'),
  User(Icons.person, '张檬'),
  User(Icons.person, '李溪芮'),
  User(Icons.person, '杨采钰'),
  User(Icons.person, '雷诺儿'),
  User(Icons.person, '霍思燕'),
  User(Icons.person, '佟大为'),
  User(Icons.person, '柳岩'),
  User(Icons.person, '罗云熙'),
  User(Icons.person, '宋茜'),
  User(Icons.person, '朱玟晞'),
  User(Icons.person, '罗正'),
  User(Icons.person, '陈意涵'),
  User(Icons.person, '陈诗敏'),
  User(Icons.person, '冯俊杰'),
  User(Icons.person, '滕文昊'),
  User(Icons.person, '王大宇'),
  User(Icons.person, '刘宇宁'),
  User(Icons.person, '杨冰怡'),
  User(Icons.person, '李宇琪'),
  User(Icons.person, '李晓东'),
  User(Icons.person, '杨幂'),
  User(Icons.person, '田牧童'),
  User(Icons.person, '蒲巴甲'),
  User(Icons.person, '何晟铭'),
  User(Icons.person, '胡博'),
  User(Icons.person, '吴芊盈'),
  User(Icons.person, '李嘉豪'),
  User(Icons.person, '雨婷儿'),
  User(Icons.person, '杜飞'),
  User(Icons.person, '吴江'),
  User(Icons.person, '王洋'),
  User(Icons.person, '王栎鑫'),
  User(Icons.person, '郭子凡'),
  User(Icons.person, '书亚信'),
  User(Icons.person, '丁泽仁'),
  User(Icons.person, '毕雯珺'),
  User(Icons.person, '郑敬基'),
  User(Icons.person, '蒋志光'),
  User(Icons.person, '贾青'),
  User(Icons.person, '黎明'),
  User(Icons.person, '杨雅涵'),
  User(Icons.person, '黄诗佳'),
  User(Icons.person, '李浩轩'),
  User(Icons.person, '刘忻'),
  User(Icons.person, '魏哲鸣'),
  User(Icons.person, '张睿'),
  User(Icons.person, '刘雅瑟'),
  User(Icons.person, '宋洋'),
  User(Icons.person, '黄一琳'),
  User(Icons.person, '孙浩'),
  User(Icons.person, '陶然'),
  User(Icons.person, '李欣泽'),
  User(Icons.person, '王子杰'),
  User(Icons.person, '王子豪'),
  User(Icons.person, '蒙恩'),
  User(Icons.person, '杜奕衡'),
  User(Icons.person, '杨紫'),
  User(Icons.person, '檀健次'),
  User(Icons.person, '张峻宁'),
  User(Icons.person, '王婧'),
  User(Icons.person, '马梦云'),
  User(Icons.person, '秦启东'),
  User(Icons.person, '柴格'),
  User(Icons.person, '林君怡'),
  User(Icons.person, '胡歌'),
  User(Icons.person, '邬俊楠'),
  User(Icons.person, '纪海星'),
  User(Icons.person, '李泉'),
  User(Icons.person, '魏华'),
  User(Icons.person, '李想'),
  User(Icons.person, '刘妍希'),
  User(Icons.person, '李漫荻'),
  User(Icons.person, '孟美岐'),
  User(Icons.person, '肖战'),
  User(Icons.person, '潘辰'),
  User(Icons.person, '夏之光'),
  User(Icons.person, '何中华'),
  User(Icons.person, '吴瑞淞'),
  User(Icons.person, '廖俊涛'),
  User(Icons.person, '张艺瀚'),
  User(Icons.person, '冯俊熙'),
  User(Icons.person, '佟梦实'),
  User(Icons.person, '迟志强'),
  User(Icons.person, '李嘉熙'),
  User(Icons.person, '张彬彬'),
  User(Icons.person, '万茜'),
  User(Icons.person, '王俊凯'),
  User(Icons.person, '马妍婷'),
  User(Icons.person, '沙宝亮'),
  User(Icons.person, '周兆渊'),
  User(Icons.person, '林思意'),
  User(Icons.person, '黄婷婷'),
  User(Icons.person, '魏嘉镁'),
  User(Icons.person, '左其铂'),
  User(Icons.person, '许佳琪'),
  User(Icons.person, '陆婷'),
  User(Icons.person, '左佳'),
  User(Icons.person, '徐立'),
  User(Icons.person, '张艺兴'),
  User(Icons.person, '黄渤'),
  User(Icons.person, '白澍'),
  User(Icons.person, '李梣溪'),
  User(Icons.person, '于朦胧'),
  User(Icons.person, '张杰'),
  User(Icons.person, '金亮'),
  User(Icons.person, '赵柯'),
  User(Icons.person, '石筱群'),
  User(Icons.person, '沈凌'),
  User(Icons.person, '许君聪'),
  User(Icons.person, '马启光'),
  User(Icons.person, '赵圆圆'),
  User(Icons.person, '肖顺尧'),
  User(Icons.person, '贡米'),
  User(Icons.person, '陈彼得'),
  User(Icons.person, '谭歆柔'),
  User(Icons.person, '白小白'),
  User(Icons.person, '刘成瑞'),
  User(Icons.person, '朱元冰'),
  User(Icons.person, '朱珠'),
  User(Icons.person, '吉丽'),
  User(Icons.person, '贺峻霖'),
  User(Icons.person, '崔健'),
  User(Icons.person, '张可盈'),
  User(Icons.person, '杨超越'),
  User(Icons.person, '高瀚宇'),
  User(Icons.person, '骆明劼'),
  User(Icons.person, '周彦辰'),
  User(Icons.person, '尹航'),
  User(Icons.person, '胡明'),
  User(Icons.person, '刘刚'),
  User(Icons.person, '高登'),
  User(Icons.person, '孙萌'),
  User(Icons.person, '王旭'),
  User(Icons.person, '王润泽'),
  User(Icons.person, '杨威'),
  User(Icons.person, '杨扬'),
  User(Icons.person, '李易峰'),
  User(Icons.person, '宁桓宇'),
  User(Icons.person, '马吟吟'),
  User(Icons.person, '秦奋'),
  User(Icons.person, '张超'),
  User(Icons.person, '程潇'),
  User(Icons.person, '熊梓淇'),
  User(Icons.person, '达娃卓玛'),
  User(Icons.person, '王太利'),
  User(Icons.person, '杨子姗'),
  User(Icons.person, '徐玺涵'),
  User(Icons.person, '马梓涵'),
  User(Icons.person, '颜敬杰'),
  User(Icons.person, '刘端端'),
  User(Icons.person, '曲尼次仁'),
  User(Icons.person, '易易紫'),
  User(Icons.person, '罗翔'),
  User(Icons.person, '吴宣仪'),
  User(Icons.person, '刘思彤'),
  User(Icons.person, '韩美娜'),
  User(Icons.person, '周艺轩'),
  User(Icons.person, '张译兮'),
  User(Icons.person, '王源'),
  User(Icons.person, '黄天崎'),
  User(Icons.person, '张晓晨'),
  User(Icons.person, '付玉龙'),
  User(Icons.person, '程前'),
  User(Icons.person, '范冰冰'),
  User(Icons.person, '胡蓉蓉'),
  User(Icons.person, '张雨鑫'),
  User(Icons.person, '林秋楠'),
  User(Icons.person, '闫桉'),
  User(Icons.person, '徐明浩'),
  User(Icons.person, 'Jony J'),
  User(Icons.person, '宫阁'),
  User(Icons.person, '李嘉格'),
  User(Icons.person, '蔡徐坤'),
  User(Icons.person, '王晴'),
  User(Icons.person, '黄德毅'),
  User(Icons.person, '林希'),
  User(Icons.person, '王啸坤'),
  User(Icons.person, '孙歆琦'),
  User(Icons.person, '美加佳'),
  User(Icons.person, '黄阅'),
  User(Icons.person, '程妮'),
  User(Icons.person, '张赫'),
  User(Icons.person, '蒋昌义'),
  User(Icons.person, '沐奕杉'),
  User(Icons.person, '池约翰'),
  User(Icons.person, '朱佳希'),
  User(Icons.person, '曾艳芬'),
  User(Icons.person, '王一博'),
  User(Icons.person, '戴景耀'),
  User(Icons.person, '贾宗超'),
  User(Icons.person, '利晴天'),
  User(Icons.person, '于晓光'),
  User(Icons.person, '杨宝心'),
  User(Icons.person, '沈思吉'),
  User(Icons.person, '蒋毓玮'),
  User(Icons.person, '陈翔'),
  User(Icons.person, '王志文'),
  User(Icons.person, '林依婷'),
  User(Icons.person, '黄圣依'),
  User(Icons.person, '腾格尔'),
  User(Icons.person, '魏晨'),
  User(Icons.person, '廖劲锋'),
  User(Icons.person, '萨顶顶'),
  User(Icons.person, '刘悦'),
  User(Icons.person, '汤斯婷'),
  User(Icons.person, '徐圣恩'),
  User(Icons.person, 'GAI'),
  User(Icons.person, '白举纲'),
  User(Icons.person, '张子文'),
  User(Icons.person, '李梦颖'),
  User(Icons.person, '方逸伦'),
  User(Icons.person, '唐九洲'),
  User(Icons.person, '马天宇'),
  User(Icons.person, '丁汀'),
  User(Icons.person, '张珊萌'),
  User(Icons.person, '刘济恺'),
  User(Icons.person, '韩玖诺'),
  User(Icons.person, '王娇'),
  User(Icons.person, '袁野'),
  User(Icons.person, '王冠'),
  User(Icons.person, '舒畅'),
  User(Icons.person, '刘亦菲'),
  User(Icons.person, '陈坤'),
  User(Icons.person, '黄奕'),
  User(Icons.person, '任嘉伦'),
  User(Icons.person, '赵薇'),
  User(Icons.person, '王梓'),
  User(Icons.person, '林弯弯'),
  User(Icons.person, '叶子淇'),
  User(Icons.person, '姚星竹'),
  User(Icons.person, '刘品言'),
  User(Icons.person, '鹿晗'),
  User(Icons.person, '丁程鑫'),
  User(Icons.person, '胡丹丹'),
  User(Icons.person, '金雯昕'),
  User(Icons.person, '毛不易'),
  User(Icons.person, '斯琴高丽'),
  User(Icons.person, '海鸣威'),
  User(Icons.person, '谭旭'),
  User(Icons.person, '徐浩'),
  User(Icons.person, '韩雪'),
  User(Icons.person, '萱萱'),
  User(Icons.person, '李明烨'),
  User(Icons.person, '次旺罗布'),
  User(Icons.person, '果芳竹'),
  User(Icons.person, '杨晓蕾'),
  User(Icons.person, '徐文洁'),
  User(Icons.person, '赵宥乔'),
  User(Icons.person, '汪闻婷'),
  User(Icons.person, '孙天宇'),
  User(Icons.person, '王安宇'),
  User(Icons.person, '吴茜'),
  User(Icons.person, '李如歌'),
  User(Icons.person, '马子洛'),
  User(Icons.person, '汤晶媚'),
  User(Icons.person, '张如意'),
  User(Icons.person, '吴博伦'),
  User(Icons.person, '许歌'),
  User(Icons.person, '庾澄庆'),
  User(Icons.person, '李诗琦'),
  User(Icons.person, '王熙然'),
  User(Icons.person, '倪新宇'),
  User(Icons.person, '雪村'),
  User(Icons.person, '郭子渝'),
  User(Icons.person, '胡兵'),
  User(Icons.person, '姜雯'),
  User(Icons.person, '付辛博'),
  User(Icons.person, '毛妮卓玛'),
  User(Icons.person, '王倩'),
  User(Icons.person, '尹馨梓'),
  User(Icons.person, '赵文浩'),
  User(Icons.person, '戚薇'),
  User(Icons.person, '火箭少女101'),
  User(Icons.person, 'Angelababy'),
  User(Icons.person, '杨嘉华'),
  User(Icons.person, '冯圣雅'),
  User(Icons.person, '武艺'),
  User(Icons.person, '罗永娟'),
  User(Icons.person, '戴向宇'),
  User(Icons.person, '薛飞'),
  User(Icons.person, '李沁谣'),
  User(Icons.person, '刘铭洋'),
  User(Icons.person, '张枫'),
  User(Icons.person, '刘人语'),
  User(Icons.person, '李艺彤'),
  User(Icons.person, '陈卓璇'),
  User(Icons.person, '王千航'),
  User(Icons.person, '费伟妮'),
  User(Icons.person, '刘些宁'),
  User(Icons.person, '于湉'),
  User(Icons.person, '曾一竣'),
  User(Icons.person, '吴俊余'),
  User(Icons.person, '邱虹凯'),
  User(Icons.person, '陆政廷'),
  User(Icons.person, '宋宇宁'),
  User(Icons.person, '王宏'),
  User(Icons.person, '陈诚'),
  User(Icons.person, '谷雨阳'),
  User(Icons.person, '霍泊宏'),
  User(Icons.person, '孔铭'),
  User(Icons.person, '姚弛'),
  User(Icons.person, 'Force嘟嘟'),
  User(Icons.person, '周庆健'),
  User(Icons.person, '张怿龙'),
  User(Icons.person, '七修远'),
  User(Icons.person, '郑润泽'),
  User(Icons.person, '王天放'),
  User(Icons.person, '吴泽'),
  User(Icons.person, '林允丞'),
  User(Icons.person, '刘炅然'),
  User(Icons.person, '谢蕾蕾'),
  User(Icons.person, '艾克拜尔·黑血'),
  User(Icons.person, '袁紫侨'),
  User(Icons.person, '周斌'),
  User(Icons.person, '李明峻'),
  User(Icons.person, '孩子王'),
  User(Icons.person, '徐晶晶'),
  User(Icons.person, '曾育茗'),
  User(Icons.person, '巩新亮'),
  User(Icons.person, '晓月老板'),
  User(Icons.person, '罗俊炜'),
  User(Icons.person, 'KC'),
  User(Icons.person, '童儿'),
  User(Icons.person, 'BB-EIGHT'),
  User(Icons.person, '徐驰成'),
  User(Icons.person, '段志豪'),
  User(Icons.person, '余宗遥'),
  User(Icons.person, '杨子轩'),
  User(Icons.person, '毕冉'),
  User(Icons.person, '于浩'),
  User(Icons.person, '曾纲杰'),
  User(Icons.person, '陈世怡'),
  User(Icons.person, '斯外戈'),
  User(Icons.person, '孔肖吟'),
  User(Icons.person, '邵星颖'),
  User(Icons.person, '高一清'),
  User(Icons.person, '毛方圆'),
  User(Icons.person, '王怡人'),
  User(Icons.person, '付梦妮'),
  User(Icons.person, '邓宁'),
  User(Icons.person, '王子异'),
  User(Icons.person, '王圆圆'),
  User(Icons.person, '刘洋影子'),
  User(Icons.person, '王紫伊'),
  User(Icons.person, '艾晓琪'),
  User(Icons.person, '李鹤'),
  User(Icons.person, '谢彬彬'),
  User(Icons.person, '闫肃'),
  User(Icons.person, '吴亦凡'),
  User(Icons.person, '李冰冰'),
  User(Icons.person, '坤音四子ONER'),
  User(Icons.person, '卜凡'),
  User(Icons.person, '灵超'),
  User(Icons.person, '木子洋'),
  User(Icons.person, '岳岳'),
  User(Icons.person, 'odyssey'),
  User(Icons.person, '王浩玮'),
  User(Icons.person, '刘佳'),
  User(Icons.person, '曾宇杰'),
  User(Icons.person, '蔡正杰'),
  User(Icons.person, '子凛'),
  User(Icons.person, '子笺'),
  User(Icons.person, '李润楠'),
  User(Icons.person, '金宜和'),
  User(Icons.person, '张茜'),
  User(Icons.person, '冯薪朵'),
  User(Icons.person, '熊万杨'),
  User(Icons.person, '张嫮目'),
  User(Icons.person, '尹清'),
  User(Icons.person, '池一骋'),
  User(Icons.person, '宋文鑫'),
  User(Icons.person, '艾克'),
  User(Icons.person, '黄柏煊'),
  User(Icons.person, '张珀凡'),
  User(Icons.person, '张燕'),
  User(Icons.person, '莫龙丹'),
  User(Icons.person, '王鲁'),
  User(Icons.person, '马蜀君'),
  User(Icons.person, '范云飞'),
  User(Icons.person, '叶子铭'),
  User(Icons.person, '龙泓昊'),
  User(Icons.person, '陈顺'),
  User(Icons.person, '陈羽洁'),
  User(Icons.person, '彭馨'),
  User(Icons.person, '李星童'),
  User(Icons.person, '李茉'),
  User(Icons.person, '娜日'),
  User(Icons.person, '王木男'),
  User(Icons.person, '夏衣旦'),
  User(Icons.person, '赵小棠'),
  User(Icons.person, '刘一隆'),
  User(Icons.person, '左卓'),
  User(Icons.person, '徐苡桉'),
  User(Icons.person, '戴煜'),
  User(Icons.person, '冷玮璐'),
  User(Icons.person, '于恩'),
  User(Icons.person, '胡睿'),
  User(Icons.person, '邓一洲'),
  User(Icons.person, '刘博朗'),
  User(Icons.person, '郭震'),
  User(Icons.person, '关健'),
  User(Icons.person, '胡彬'),
  User(Icons.person, '童芋菱'),
  User(Icons.person, '黄亮辉'),
  User(Icons.person, '郭岱鑫'),
  User(Icons.person, '于翔北'),
  User(Icons.person, '北姬子'),
  User(Icons.person, '邓泽鸣'),
  User(Icons.person, 'Ku'),
  User(Icons.person, '徐梦圆'),
  User(Icons.person, '山城浩二'),
  User(Icons.person, '张承'),
  User(Icons.person, '巫迪文'),
  User(Icons.person, '周峻宇'),
  User(Icons.person, 'Young Gee'),
  User(Icons.person, '李袁杰'),
  User(Icons.person, '陈雪枫'),
  User(Icons.person, '文兆杰'),
  User(Icons.person, '郭鑫磊'),
  User(Icons.person, '张兆艺'),
  User(Icons.person, '马嘉祺'),
  User(Icons.person, '张洢豪'),
];


final letters = <String>[
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z"
];

class DemoPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return AddrBook();
  }
}


class AddrBook extends StatefulWidget {
  AddrBook() {
    usrs.sort((a, b) {
      return a.name.compareTo(b.name);
    });
  }
  @override
  State<StatefulWidget> createState() {
    return AddrBookState();
  }
}

class AddrBookState extends State<AddrBook> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: Stack(
          overflow: Overflow.visible,
          children: <Widget>[
          ListView.builder(
            itemCount: usrs.length,
            itemBuilder: (BuildContext context, int index) {
              return Container(
                decoration: BoxDecoration(
                    border: Border(
                        bottom:
                            BorderSide(color: Color(0xFFDFDFDF), width: .5))),
                padding: index == 0
                    ? EdgeInsets.only(left: 40, top: 8, bottom: 4)
                    : EdgeInsets.only(left: 40, top: 4, bottom: 4),
                child: Row(
                  children: <Widget>[
                    Container(
                        decoration: BoxDecoration(
                            color: Color(0xFFCCCCCC),
                            borderRadius:
                                BorderRadius.all(Radius.circular(100))),
                        padding: EdgeInsets.all(10),
                        child: Icon(
                          usrs[index].icon,
                          size: 40,
                          color: Colors.white,
                        )),
                    Container(
                        margin: EdgeInsets.only(left: 16),
                        child: Text(usrs[index].name))
                  ],
                ),
              );
            },
          ),
          Positioned(
            right: 0,
            top: 30,
            child: Container(
              width: 50,
              height: MediaQuery.of(context).size.height - 60,
              child: LetterList(),
            ),
          )
        ]),
      ),
    );
  }
}

class LetterList extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new LetterListState();
  }
}

class LetterListState extends State<LetterList> {
  @override
  Widget build(BuildContext context) {
    return Container(
//      decoration: BoxDecoration(color: Colors.red),
      width: 40,
      child: ListView.builder(
        itemCount: letters.length,
        itemBuilder: (BuildContext context, int index) {
          return Padding(
            padding: EdgeInsets.all(4),
            child: Text(letters[index], style: TextStyle(color: Colors.black, fontSize: 12), textAlign: TextAlign.center,),
          );
      }),
    );
  }
}